// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParseContent(arg1) {
  return window['go']['handlers']['DocumentHandler']['ParseContent'](arg1);
}

export function SerializeNode(arg1) {
  return window['go']['handlers']['DocumentHandler']['SerializeNode'](arg1);
}

export function SetContext(arg1) {
  return window['go']['handlers']['DocumentHandler']['SetContext'](arg1);
}
