// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {context} from '../models';

export function ParseContent(arg1:string):Promise<core.FileNode>;

export function SerializeNode(arg1:core.FileNode):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
