// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CancelRequest(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function Execute(arg1:core.Request,arg2:core.Environment,arg3:core.ExecutionOptions):Promise<core.Response>;

export function GetHistory(arg1:number):Promise<Array<core.HistoryEntry>>;
