// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1, arg2) {
  return window['go']['handlers']['ExecutionHandler']['Cancel'](arg1, arg2);
}

export function Execute(arg1, arg2, arg3) {
  return window['go']['handlers']['ExecutionHandler']['Execute'](arg1, arg2, arg3);
}
