// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {core} from '../models';

export function Cancel(arg1:context.Context,arg2:string):Promise<void>;

export function Execute(arg1:context.Context,arg2:core.Request,arg3:core.Environment):Promise<core.Response>;
