// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRequest(arg1) {
  return window['go']['handlers']['ExecutionHandler']['CancelRequest'](arg1);
}

export function ClearHistory() {
  return window['go']['handlers']['ExecutionHandler']['ClearHistory']();
}

export function Execute(arg1, arg2, arg3) {
  return window['go']['handlers']['ExecutionHandler']['Execute'](arg1, arg2, arg3);
}

export function GetHistory(arg1) {
  return window['go']['handlers']['ExecutionHandler']['GetHistory'](arg1);
}
