// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportWorkspace(arg1, arg2) {
  return window['go']['handlers']['ImportExportHandler']['ExportWorkspace'](arg1, arg2);
}

export function ImportPostmanCollection(arg1, arg2) {
  return window['go']['handlers']['ImportExportHandler']['ImportPostmanCollection'](arg1, arg2);
}

export function ImportPostmanEnvironment(arg1, arg2) {
  return window['go']['handlers']['ImportExportHandler']['ImportPostmanEnvironment'](arg1, arg2);
}
