// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ExportWorkspace(arg1:context.Context,arg2:string,arg3:string):Promise<void>;

export function ImportPostmanCollection(arg1:context.Context,arg2:string,arg3:string):Promise<void>;

export function ImportPostmanEnvironment(arg1:context.Context,arg2:string,arg3:string):Promise<void>;
