// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportWorkspace(arg1:string,arg2:string):Promise<void>;

export function ImportPostmanCollection(arg1:string,arg2:string):Promise<void>;

export function ImportPostmanEnvironment(arg1:string,arg2:string):Promise<void>;
