// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentWorkspace(arg1, arg2) {
  return window['go']['handlers']['WorkspaceHandler']['AddRecentWorkspace'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['handlers']['WorkspaceHandler']['CreateFolder'](arg1);
}

export function Delete(arg1) {
  return window['go']['handlers']['WorkspaceHandler']['Delete'](arg1);
}

export function GetCollections() {
  return window['go']['handlers']['WorkspaceHandler']['GetCollections']();
}

export function GetCurrentWorkspace() {
  return window['go']['handlers']['WorkspaceHandler']['GetCurrentWorkspace']();
}

export function GetEnvironments() {
  return window['go']['handlers']['WorkspaceHandler']['GetEnvironments']();
}

export function GetMetadata(arg1) {
  return window['go']['handlers']['WorkspaceHandler']['GetMetadata'](arg1);
}

export function GetRecentWorkspaces() {
  return window['go']['handlers']['WorkspaceHandler']['GetRecentWorkspaces']();
}

export function GetWorkspaceMetadata() {
  return window['go']['handlers']['WorkspaceHandler']['GetWorkspaceMetadata']();
}

export function OpenWorkspace(arg1) {
  return window['go']['handlers']['WorkspaceHandler']['OpenWorkspace'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['handlers']['WorkspaceHandler']['ReadFile'](arg1);
}

export function RemoveRecentWorkspace(arg1) {
  return window['go']['handlers']['WorkspaceHandler']['RemoveRecentWorkspace'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['handlers']['WorkspaceHandler']['Rename'](arg1, arg2);
}

export function SaveEnvironments(arg1) {
  return window['go']['handlers']['WorkspaceHandler']['SaveEnvironments'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['handlers']['WorkspaceHandler']['SaveFile'](arg1, arg2);
}

export function SaveMetadata(arg1, arg2) {
  return window['go']['handlers']['WorkspaceHandler']['SaveMetadata'](arg1, arg2);
}

export function SaveWorkspaceMetadata(arg1) {
  return window['go']['handlers']['WorkspaceHandler']['SaveWorkspaceMetadata'](arg1);
}
