// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {core} from '../models';

export function GetCollections(arg1:context.Context):Promise<Array<core.Collection>>;

export function OpenWorkspace(arg1:context.Context,arg2:string):Promise<void>;
