// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CreateFolder(arg1:string):Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function GetCollections():Promise<Array<core.Collection>>;

export function GetEnvironments():Promise<Array<core.Environment>>;

export function GetMetadata(arg1:string):Promise<string>;

export function GetWorkspaceMetadata():Promise<core.WorkspaceMetadata>;

export function OpenWorkspace(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveMetadata(arg1:string,arg2:string):Promise<void>;

export function SaveWorkspaceMetadata(arg1:core.WorkspaceMetadata):Promise<void>;
