// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCollections(arg1) {
  return window['go']['handlers']['WorkspaceHandler']['GetCollections'](arg1);
}

export function OpenWorkspace(arg1, arg2) {
  return window['go']['handlers']['WorkspaceHandler']['OpenWorkspace'](arg1, arg2);
}
