// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CancelRequest(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function Execute(arg1:core.Request,arg2:core.Environment,arg3:core.ExecutionOptions):Promise<core.Response>;

export function GetCollections():Promise<Array<core.Collection>>;

export function GetHistory(arg1:number):Promise<Array<core.HistoryEntry>>;

export function GetSettings():Promise<string>;

export function GetWindowState():Promise<core.WindowState>;

export function GetWorkspaceMetadata():Promise<core.WorkspaceMetadata>;

export function OpenWorkspace(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveWindowState(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SaveWorkspaceMetadata(arg1:core.WorkspaceMetadata):Promise<void>;

export function SelectDirectory():Promise<string>;

export function ShowInFolder(arg1:string):Promise<void>;

export function UpdateSettings(arg1:string):Promise<void>;
