// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function Execute(arg1:core.Request,arg2:core.Environment):Promise<core.Response>;
