// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRequest(arg1) {
  return window['go']['main']['App']['CancelRequest'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function Execute(arg1, arg2, arg3) {
  return window['go']['main']['App']['Execute'](arg1, arg2, arg3);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function GetWorkspaceMetadata() {
  return window['go']['main']['App']['GetWorkspaceMetadata']();
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveWindowState(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2, arg3);
}

export function SaveWorkspaceMetadata(arg1) {
  return window['go']['main']['App']['SaveWorkspaceMetadata'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
